apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubernetes-w9
  namespace: default
spec:
  interval: 30s
  url: https://github.com/mikesir87/sample-flux-manifests.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubernetes-w9
  namespace: default
spec:
  interval: 5m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: kubernetes-w9
  path: "./"
  prune: true
